import assert from 'node:assert/strict';
import {items,capacity,feedback} from '../js/data/agile.js';
import {available,sprintTasks,validSelection,validAdaptation,delivered,proposedPriority} from '../js/data/engine.js';
assert.equal(items.length,10);
assert.equal(new Set(items.map(x=>x.id)).size,10);
assert.equal(capacity.reduce((a,b)=>a+b,0),8);
assert.equal(sprintTasks(['US-01','US-02']).length,4);
const state={priorities:Object.fromEntries(items.map(x=>[x.id,x.priority])),sprints:{}};
assert.equal(available(state,1).length,6);
assert.equal(validSelection(state,1,['US-01','US-02']),true);
assert.equal(validSelection(state,1,['US-02','US-04']),false);
assert.equal(validSelection(state,1,['US-01','US-01']),false);
state.sprints[1]={selected:['US-01','US-02'],review:true,adapted:true};
assert.equal(available(state,2).some(x=>x.id==='US-01'),false);
assert.equal(validSelection(state,2,['US-03','US-04']),true);
assert.equal(proposedPriority(state,'US-03',2),'Must');
assert.equal(validAdaptation(1,'US-03'),true);
assert.equal(validAdaptation(1,'ignore'),false);
assert.equal(validAdaptation(4,'none'),true);
assert.equal(delivered(state,1).size,2);
assert.equal(feedback.length,4);
console.log('PASS: v8 scenario, planning, capacity, delivery, feedback and adaptation rules');
