import {backlogItems} from '../data/content.js';
import {state,save,award} from '../core/state.js';
import {intro,objective,completed,escapeHTML,$,$$,notice} from '../core/helpers.js';
const categories=['Must','Should','Could','Won’t now'];
const stageItems=n=>backlogItems.filter(x=>x.sprint===n);
const isCorrect=x=>state.priorities[x.id]===x.priority;
export function render(){const stage=state.backlogStage||1,items=stageItems(stage),checked=state.backlogChecked[stage]===true,correct=items.filter(isCorrect).length;
return intro('MISSION 02 • PRODUCT BACKLOG','Prioritise across four Sprints.','Work through Sprint 1, 2, 3 and 4 in order. This is a teaching exercise: the Product Backlog stays one evolving list; the four tabs group the items for practice.')+
objective('Classify every backlog item',`Sprint ${stage} of 4 · ${correct} / ${items.length} correct. Choose MoSCoW priorities; click Check to see exactly which entries need revision.`)+
`<section class="card"><div class="sprint-tabs" aria-label="Backlog practice stages">${[1,2,3,4].map(n=>`<button type="button" data-backlog-stage="${n}" class="sprint-tab ${n===stage?'active':''} ${state.backlogChecked[n]?'passed':''}" ${n>1&&!state.backlogChecked[n-1]?'disabled':''} aria-current="${n===stage?'step':'false'}">Sprint ${n} ${state.backlogChecked[n]?'✓':''}</button>`).join('')}</div><h2>Sprint ${stage} · ${['Discovery & design','Core application','Reporting & automation','Verification & handoff'][stage-1]}</h2><p class="muted">Select a priority for every item. Enablers are technical/project work, not learner-facing user stories. The deferred chatbot is shown to practise excluding out-of-scope work.</p><div class="table-wrap"><table><thead><tr><th>ID / type</th><th>Backlog item</th><th>MoSCoW priority</th><th>Feedback</th></tr></thead><tbody>${items.map(x=>{const value=state.priorities[x.id]||'',hasChecked=Boolean(state.backlogAttempted?.[stage]),valid=isCorrect(x);return `<tr><td><b>${x.id}</b><br><small>${escapeHTML(x.kind)}</small></td><td>${escapeHTML(x.want)}</td><td><select data-priority="${x.id}" aria-label="Priority for ${x.id}" ${checked?'disabled':''}><option value="">Choose…</option>${categories.map(c=>`<option value="${c}" ${value===c?'selected':''}>${c}</option>`).join('')}</select></td><td class="priority-feedback" id="feedback-${x.id}">${checked?'<span class="good-text">✓ Correct</span>':hasChecked?(valid?'<span class="good-text">✓ Correct</span>':`<span class="bad-text">✗ ${value?'Incorrect':'Missing'}. Expected: <b>${escapeHTML(x.priority)}</b>.<br>${escapeHTML(x.reason)}</span>`):'<span class="muted">Awaiting check</span>'}</td></tr>`}).join('')}</tbody></table></div><div class="actions"><span class="muted">${correct} / ${items.length} correct</span><button type="button" class="btn primary" id="check-backlog" ${checked?'disabled':''}>${checked?'✓ Sprint stage validated':'Check Sprint '+stage+' priorities'}</button>${checked&&stage<4?`<button type="button" class="btn primary" id="next-backlog">Continue to Sprint ${stage+1} →</button>`:''}</div><div id="backlog-feedback" aria-live="polite">${checked?notice(stage<4?'This Sprint is validated. You can revisit it using the Sprint tabs, or continue to the next Sprint.':'All four Sprint stages validated. Use the Sprint tabs to review earlier answers.'):''}</div></section>`+(state.backlogDone?completed('All four backlog stages validated. The four Sprint simulations are unlocked.','sprint1'):'')}
export function bind(refresh){$$('[data-backlog-stage]').forEach(el=>el.addEventListener('click',()=>{const n=Number(el.dataset.backlogStage);if(n>1&&!state.backlogChecked[n-1])return;state.backlogStage=n;save();refresh()}));$$('[data-priority]').forEach(el=>el.addEventListener('change',()=>{state.priorities[el.dataset.priority]=el.value;save();if(state.backlogAttempted?.[state.backlogStage])refresh()}));$('#check-backlog')?.addEventListener('click',()=>{const stage=state.backlogStage||1,items=stageItems(stage);state.backlogAttempted={...(state.backlogAttempted||{}),[stage]:true};if(items.every(isCorrect)){state.backlogChecked[stage]=true;if(stage===4){state.backlogDone=true;award('backlog',110)}else save();refresh();return;}save();refresh();$('#backlog-feedback').innerHTML=notice('Some answers need revision. Red feedback shows the expected category and explains why. Correct the entries and check again.','warn');});$('#next-backlog')?.addEventListener('click',()=>{if(!state.backlogChecked[state.backlogStage])return;state.backlogStage++;save();refresh()})}
