import {state,save,award,sprintState,taskStatus,setTask,sprintFinished} from '../core/state.js';
import {byId,plannedFor,sprintTasks,proposedPriority,validSelection,validAdaptation,delivered} from '../data/engine.js';
import {sprintGoals,sprintLengths,feedback,rejectedInSprint1} from '../data/agile.js';
import {intro,objective,completed,escapeHTML,$,$$,notice} from '../core/helpers.js';
const h=escapeHTML;
const nextStage={todo:'doing',doing:'review',review:'done'};
const previousStage={doing:'todo',review:'doing',done:'review'};
const actionLabel={todo:'Advance →',doing:'Submit for Review →',review:'Accept as Done ✓'};

function selection(n,ss){
 const expected=plannedFor(state,n);
 if(!ss.selected.length)ss.selected=[...expected];
 const carry=n===2&&expected.includes('US-04');
 return `<section class="card"><span class="eyebrow">SPRINT PLANNING · GUIDED BACKLOG</span><h2>Use the dictated Sprint ${n} Product Backlog</h2><p><strong>Sprint Goal:</strong> ${h(sprintGoals[n-1])}</p><p><strong>Sprint length:</strong> ${h(sprintLengths[n-1].label)} · ${sprintLengths[n-1].days} days</p><p class="muted">Version 9 intentionally distributes the 9 active Product Backlog items across the month so learners can focus on how work flows through Scrum. ${carry?'US-04 is included as a carry-forward item because Sprint 1 Review rejected its Definition of Done.':''}</p><div class="pick-grid">${expected.map(id=>`<label class="pick-card fixed-pick"><input type="checkbox" checked disabled><span><b>${id} · ${h(byId(id).title)}</b><small>${n===2&&id==='US-04'?'↪ Carry-forward from Sprint 1 Review':'Planned for this Sprint'} · Current priority: ${h(proposedPriority(state,id,n))}</small></span></label>`).join('')}</div><p class="muted"><b>${expected.length}</b> Product Backlog item${expected.length===1?'':'s'} in this Sprint${carry?' (including 1 carry-forward)':''}.</p><button class="btn primary" id="plan">Confirm Sprint ${n} Backlog · +30 XP</button><div id="plan-feedback" aria-live="polite"></div></section>`
}

function board(n,ss){
 const tasks=sprintTasks(ss.selected,n),done=tasks.filter(t=>taskStatus(n,t.id)==='done').length;
 return `<section class="card"><span class="eyebrow">SPRINT EXECUTION · BUILD AND TEST</span><h2>Deliver a tested Increment</h2><p class="muted">${done} / ${tasks.length} tasks accepted as Done. Move work through the board. In Sprint 1, one planned DoD rejection is used to demonstrate carry-forward.</p><div class="board board-compact">${[['todo','To do'],['doing','In progress'],['review','Review (Peer Review)'],['done','Done ✓']].map(([status,label])=>`<section class="lane"><h3>${label}</h3>${tasks.filter(t=>taskStatus(n,t.id)===status).map(t=>`<article class="task"><span class="eyebrow">${h(t.id)} · ${h(t.parent)}</span><strong>${h(t.title)}</strong>${status==='review'?'<p class="task-note">Compare this work with its acceptance criteria and Definition of Done.</p>':''}${n===1&&t.id===rejectedInSprint1.task&&ss.blockerSeen?'<p class="notice warn"><b>Review rejection:</b> dashboard counts/date ordering failed the DoD check. This task cannot be accepted in Sprint 1.</p>':''}<div class="task-actions">${previousStage[status]?`<button class="mini" data-task="${t.id}" data-next="${previousStage[status]}">← Back</button>`:''}${nextStage[status]?`<button class="mini primary-mini" data-task="${t.id}" data-next="${nextStage[status]}">${actionLabel[status]}</button>`:''}</div></article>`).join('')||'<p class="empty">No tasks here</p>'}</section>`).join('')}</div></section>`
}

function readyForReview(n,ss){
 const tasks=sprintTasks(ss.selected,n);
 if(n===1){return tasks.every(t=>t.id===rejectedInSprint1.task?taskStatus(n,t.id)==='review'&&ss.blockerSeen:taskStatus(n,t.id)==='done')}
 return tasks.every(t=>taskStatus(n,t.id)==='done');
}

function inspect(n,ss){
 const ready=readyForReview(n,ss),f=feedback[n-1];
 return `<div class="grid two review-block"><section class="card"><span class="eyebrow">SPRINT REVIEW · INSPECT INCREMENT</span><h2>Demonstrate working outcomes</h2>${!ready?notice(n===1?'Complete the accepted work and encounter the planned US-04 DoD rejection before the Sprint Review.':'Complete and verify all Sprint tasks before the review.','warn'):`<p class="muted">The team demonstrates the Sprint Increment. Maya responds:</p><blockquote>“${h(f.quote)}”</blockquote>${n===1?'<div class="notice warn"><b>DoD decision:</b> US-04 is rejected in Sprint 1. It returns to the Product Backlog and will appear in Sprint 2 with corrective Sprint Backlog tasks.</div>':''}<fieldset class="question"><legend>What should the team do with this review evidence?</legend><label class="option"><input type="radio" name="review-answer" value="inspect" ${ss.reviewAnswer==='inspect'?'checked':''}> Inspect the Increment and adapt the Product Backlog / next Sprint.</label><label class="option"><input type="radio" name="review-answer" value="ignore" ${ss.reviewAnswer==='ignore'?'checked':''}> Ignore it because the monthly plan was written earlier.</label></fieldset><button class="btn primary" id="review" ${ss.review?'disabled':''}>${ss.review?'✓ Review recorded':'Record Sprint Review · +40 XP'}</button><div id="review-feedback" aria-live="polite"></div>`}</section><section class="card"><span class="eyebrow">RETROSPECTIVE · IMPROVE HOW WE WORK</span><h2>Choose one team improvement</h2><p class="muted">The Retrospective improves the process; it is different from the product decision made in Review.</p><select id="retro-choice" ${!ss.review||ss.retro?'disabled':''}><option value="">Choose a process improvement…</option><option value="small" ${ss.improvement==='small'?'selected':''}>Split oversized tasks earlier</option><option value="test" ${ss.improvement==='test'?'selected':''}>Review acceptance checks sooner</option><option value="block" ${ss.improvement==='block'?'selected':''}>Raise blockers in daily check-ins</option></select><button class="btn primary" id="retro" ${!ss.review||ss.retro?'disabled':''}>${ss.retro?'✓ Improvement recorded':'Record Retrospective · +40 XP'}</button></section></div>`
}

function adaptation(n,ss){
 if(!ss.review||!ss.retro)return '';
 const f=feedback[n-1],target=f.target;
 return `<section class="card adapt-card"><span class="eyebrow">INSPECT → ADAPT · PRODUCT BACKLOG</span><h2>${n===4?'Inspect what remains':'Update what happens next'}</h2><p class="muted">${h(f.reason)}</p>${target?`<p><strong>Backlog decision:</strong> ${h(byId(target).title)}</p><label for="adapt-choice">What should the Product Owner do?</label><select id="adapt-choice" ${ss.adapted?'disabled':''}><option value="">Choose a response…</option><option value="${target}" ${ss.adaptChoice===target?'selected':''}>${n===1?'Carry US-04 into Sprint 2 for correction and re-verification':`Keep ${target} visible at the required priority for the next planned Sprint`}</option><option value="ignore" ${ss.adaptChoice==='ignore'?'selected':''}>Ignore the review evidence</option></select>`:`<p>US-10 remains visible as Won’t now. Future ideas can stay in the Product Backlog after this classroom month.</p><label for="adapt-choice">What should happen to unfinished/deferred items?</label><select id="adapt-choice" ${ss.adapted?'disabled':''}><option value="">Choose a response…</option><option value="none" ${ss.adaptChoice==='none'?'selected':''}>Keep them visible for future Product Backlog refinement</option><option value="ignore" ${ss.adaptChoice==='ignore'?'selected':''}>Claim every idea was delivered</option></select>`}<button class="btn primary" id="adapt" ${ss.adapted?'disabled':''}>${ss.adapted?'✓ Adaptation recorded':'Confirm adaptation · +35 XP'}</button><div id="adapt-feedback" aria-live="polite"></div></section>`
}

export function render(n){
 const ss=sprintState(n),prev=delivered(state,n-1),count=plannedFor(state,n).length;
 return intro(`SPRINT ${n} · ${sprintLengths[n-1].label}`,`Sprint ${n}: Build, inspect, adapt.`,sprintGoals[n-1])+objective('Deliver a usable, verified Increment',`This Sprint lasts ${sprintLengths[n-1].days} days (${sprintLengths[n-1].label}). Version 9 provides the Product Backlog allocation; your job is to experience planning, execution, Review, Retrospective and adaptation.`)+`<div class="stats"><div class="stat"><b>${count}</b><span>Product Backlog items</span></div><div class="stat"><b>${sprintLengths[n-1].days}</b><span>Sprint days</span></div><div class="stat"><b>${prev.size}</b><span>Previously accepted items</span></div><div class="stat"><b>${ss.planned?'Planned':'Open'}</b><span>Sprint Backlog</span></div></div>${ss.planned?`<section class="card"><h2>Selected Sprint Backlog</h2><div class="legend">${ss.selected.map(id=>`<span class="pill">${n===2&&id==='US-04'?'↪ ':''}${h(id)} · ${h(byId(id).title)}</span>`).join('')}</div><p class="muted">${n===2&&ss.selected.includes('US-04')?'US-04 is a review-driven carry-forward. Its Sprint 2 tasks are corrective work and re-verification. ':''}These items support the current Sprint Goal.</p></section>${board(n,ss)}${inspect(n,ss)}${adaptation(n,ss)}`:selection(n,ss)}${sprintFinished(n)?completed(`Sprint ${n} completed. Review evidence has informed what happens next.`,n<4?`sprint${n+1}`:'final'):''}`
}

export function bind(n,refresh){
 const ss=sprintState(n);
 $('#plan')?.addEventListener('click',()=>{ss.selected=[...plannedFor(state,n)];if(!validSelection(state,n,ss.selected)){$('#plan-feedback').innerHTML=notice('The guided Sprint allocation is incomplete.','warn');return}ss.planned=true;award(`plan-${n}`,30);refresh()});
 $$('[data-task]').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.task,next=el.dataset.next,current=taskStatus(n,id);if(!sprintTasks(ss.selected,n).some(t=>t.id===id)||!(nextStage[current]===next||previousStage[current]===next))return;if(n===1&&id===rejectedInSprint1.task&&current==='review'&&next==='done'){ss.blockerSeen=true;ss.rejectedPbi=rejectedInSprint1.pbi;save();refresh();return}setTask(n,id,next);refresh()}));
 $$('input[name="review-answer"]').forEach(el=>el.addEventListener('change',()=>{ss.reviewAnswer=el.value;save()}));
 $('#review')?.addEventListener('click',()=>{if(!readyForReview(n,ss))return;if(ss.reviewAnswer!=='inspect'){$('#review-feedback').innerHTML=notice('Use the Sprint Review evidence to inspect the product and adapt what happens next.','warn');return}if(n===1)ss.rejectedPbi=rejectedInSprint1.pbi;ss.review=true;award(`review-${n}`,40);refresh()});
 $('#retro')?.addEventListener('click',()=>{const value=$('#retro-choice').value;if(!ss.review||!value)return;ss.improvement=value;ss.retro=true;award(`retro-${n}`,40);refresh()});
 $('#adapt-choice')?.addEventListener('change',el=>{ss.adaptChoice=el.target.value;save()});
 $('#adapt')?.addEventListener('click',()=>{if(!ss.review||!ss.retro)return;if(!validAdaptation(n,ss.adaptChoice)){$('#adapt-feedback').innerHTML=notice('Use the Review evidence to make the intended Product Backlog decision.','warn');return}ss.adapted=true;award(`adapt-${n}`,35);refresh()});
}
