import {stories} from '../data/content.js';
import {state,save,award} from '../core/state.js';
import {intro,objective,completed,escapeHTML,$,$$,notice} from '../core/helpers.js';

const optionsFor=(s,index)=>{
 const wrong=stories.filter(x=>x.id!==s.id);
 const other=wrong[(index+2)%wrong.length], another=wrong[(index+5)%wrong.length];
 return [s.why,other.why,another.why].map((value,i)=>({value,correct:i===0})).sort((a,b)=>((index*7+ (a.correct?2:a.value.length))%11)-((index*7+(b.correct?2:b.value.length))%11));
};
// Every item is answered independently; no exact sentence typing is required.
export function render(){const count=stories.filter(s=>s.sprint).filter(s=>state.storyAnswers[s.id]==='correct').length;
 return intro('MISSION 01 • USER STORIES','Build nine user stories.','Choose the purpose that completes each SmartStudy user story. The role and capability are provided; your task is to recognise the learner value.')+
 objective('Complete all nine stories',`Progress: ${count} / 9. Each card must be answered correctly before you can advance. Read the acceptance criteria to see how the story can be tested.`)+
 `<section class="story-quest-grid">${stories.filter(s=>s.sprint).map((s,index)=>{const opts=optionsFor(s,index),done=state.storyAnswers[s.id]==='correct';return `<article class="card story-question" id="card-${s.id}"><div class="toolbar"><span class="pill">${s.id}</span><span class="pill ${done?'success':'pending'}">${done?'✓ Completed':'Not completed'}</span></div><h2>As a ${escapeHTML(s.role)}, I want to ${escapeHTML(s.want)}…</h2><p><b>…so that:</b></p><fieldset class="question"><legend class="sr-only">Choose the reason for ${s.id}</legend>${opts.map((o,j)=>`<label class="option"><input type="radio" name="answer-${s.id}" value="${j}" ${done?'disabled':''}> ${escapeHTML(o.value)}</label>`).join('')}</fieldset><button type="button" class="btn ${done?'outline':'primary'}" data-check-story="${s.id}" ${done?'disabled':''}>${done?'✓ Story complete':'Check this story'}</button><div data-story-feedback="${s.id}" aria-live="polite">${done?notice('Correct! This reason describes the value of the capability.','good'):''}</div><details><summary>How could we test this story?</summary><ul class="criteria">${s.criteria.map(c=>`<li>${escapeHTML(c)}</li>`).join('')}</ul></details></article>`}).join('')}</section><div class="checkpoint"><h2>Story workshop: ${count} / 9 complete</h2><p>Complete every card to unlock the Product Backlog. No memorisation or exact sentence matching required.</p></div>`+(state.storyDone?completed('All nine SmartStudy stories are understood. Now order the Product Backlog.','backlog'):'')
}
export function bind(refresh){$$('[data-check-story]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.checkStory;const s=stories.find(x=>x.id===id);if(!s||state.storyAnswers[id]==='correct')return;const selected=$(`input[name="answer-${id}"]:checked`);const feedback=$(`[data-story-feedback="${id}"]`);if(!selected){feedback.innerHTML=notice('Select one reason first.','warn');return;}const correct=optionsFor(s,stories.filter(x=>x.sprint).findIndex(x=>x.id===id))[Number(selected.value)]?.correct;if(!correct){feedback.innerHTML=notice('Not quite. Look for the reason that directly explains the benefit of this capability to its user. Try again.','warn');return;}state.storyAnswers[id]='correct';if(stories.filter(x=>x.sprint).every(x=>state.storyAnswers[x.id]==='correct')){state.storyDone=true;award('story',90)}else save();refresh();}));}
